name: Update WT

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update to (e.g., 4.13.0)'
        type: string
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update:
    uses: ./.github/workflows/update-package.yaml
    with:
      package: wt
      owner: emweb
      repo: wt
      version: ${{ inputs.version }}
